anmeldung refactor and fix errors
Layer-Four/handwerker_app pull request #31
Opened 2024-07-18 09:50 UTC by obaidajarrah

2024-07-19 07:56 UTC, Mm-lay4 requested changes

2024-07-19 07:56 UTC, Mm-lay4 commented on lib/view/login_screen/login_view.dart
> +    const emailRegex = r"""^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+""";
Hier is das gleiche Problem wie in der Web App.
Befehle Doppeln sich und die Filter anweisung des Domainbereichs lässt keine -_ zu

2024-07-19 07:56 UTC, Mm-lay4 commented on lib/view/login_screen/set_password.dart
> +// final passwordVisibilityProvider = StateProvider((ref) => false);
Schön das du hier ein Provider einbindest, aber Denke Provider für diese Seite hat etwas mehr zu tun als nur die Sichtbarkeit zu regeln

2024-07-21 10:47 UTC, obaidajarrah commented on lib/view/login_screen/login_view.dart
> +    const emailRegex = r"""^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+""";
const emailRegex = r"^[a-zA-Z0-9.!#$%&'*+/=?^_{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$";
hoffentlich geht so

2024-07-22 08:44 UTC, Mm-lay4 approved these changes

2024-07-22 08:45 UTC, merged